/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapp;

import javaapp.multichoice;
import static javaapp.identification.idenQ1;
import static javaapp.identification.idenQ2;
import static javaapp.identification.idenQ3;
import static javaapp.identification.idenQ4;
import static javaapp.identification.idenQ5;
import static javaapp.identification.idenSCORE;

/**
 *
 * @author nejac
 */
public class correctidentification extends javax.swing.JFrame {

    public correctidentification() {
        initComponents();
        String idenKEY1 = "CRISOSTOMO IBARRA";
        String idenKEY2 = "SIMOUN";
        String idenKEY3 = "ELIAS";
        String idenKEY4 = "MARIA CLARA";
        String idenKEY5 = "PADRE DAMASO";
        String idenANS1 = idenQ1.getText();
        String idenANS2 = idenQ2.getText();
        String idenANS3 = idenQ3.getText();
        String idenANS4 = idenQ4.getText();
        String idenANS5 = idenQ5.getText();

        if (idenANS1.equals(idenKEY1))        
            correct1.setText("CORRECT");        
        if (idenANS2.equals(idenKEY2))           
            correct2.setText("CORRECT");        
        if (idenANS3.equals(idenKEY3))            
            correct3.setText("CORRECT");       
        if (idenANS4.equals(idenKEY4))            
            correct4.setText("CORRECT");       
        if (idenANS5.equals(idenKEY5))           
            correct5.setText("CORRECT");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NEIL1 = new javax.swing.JTextField();
        question1 = new javax.swing.JLabel();
        NEIL2 = new javax.swing.JTextField();
        question4 = new javax.swing.JLabel();
        NEIL3 = new javax.swing.JTextField();
        question2 = new javax.swing.JLabel();
        question3 = new javax.swing.JLabel();
        NEIL4 = new javax.swing.JTextField();
        question5 = new javax.swing.JLabel();
        NEIL5 = new javax.swing.JTextField();
        nextbuttonIDEN = new javax.swing.JButton();
        correct1 = new javax.swing.JTextField();
        correct2 = new javax.swing.JTextField();
        correct3 = new javax.swing.JTextField();
        correct4 = new javax.swing.JTextField();
        correct5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(251, 240, 229));
        jPanel1.setPreferredSize(new java.awt.Dimension(536, 387));

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 82, 75));
        jLabel1.setText("Your answers are case sensitive, type it in all CAPS.");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 82, 75));
        jLabel3.setText("IDENTIFICATION");

        NEIL1.setEditable(false);
        NEIL1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        NEIL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEIL1ActionPerformed(evt);
            }
        });

        question1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        question1.setForeground(new java.awt.Color(108, 82, 75));
        question1.setText("1. Who is the main protagonist in Noli Me Tangere?");

        NEIL2.setEditable(false);
        NEIL2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        NEIL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEIL2ActionPerformed(evt);
            }
        });

        question4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        question4.setForeground(new java.awt.Color(108, 82, 75));
        question4.setText("4. Who was Ibarra going to marry?");

        NEIL3.setEditable(false);
        NEIL3.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        NEIL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEIL3ActionPerformed(evt);
            }
        });

        question2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        question2.setForeground(new java.awt.Color(108, 82, 75));
        question2.setText("2. Which character is a wealthy yet mysterious jeweler in El Filibusterismo?");

        question3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        question3.setForeground(new java.awt.Color(108, 82, 75));
        question3.setText("3. Who is the fugitive ally of Ibarra in Noli Me Tangere?");

        NEIL4.setEditable(false);
        NEIL4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        NEIL4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEIL4ActionPerformed(evt);
            }
        });

        question5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        question5.setForeground(new java.awt.Color(108, 82, 75));
        question5.setText("5. Who is the arrogant and power hungry friar in Noli me Tangere?");

        NEIL5.setEditable(false);
        NEIL5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        NEIL5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEIL5ActionPerformed(evt);
            }
        });

        nextbuttonIDEN.setBackground(new java.awt.Color(108, 82, 75));
        nextbuttonIDEN.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        nextbuttonIDEN.setText("NEXT");
        nextbuttonIDEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonIDENActionPerformed(evt);
            }
        });

        correct1.setEditable(false);
        correct1.setBackground(new java.awt.Color(251, 240, 229));
        correct1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correct1.setForeground(new java.awt.Color(47, 110, 31));
        correct1.setText("CRISOSTOMO IBARRA");
        correct1.setBorder(null);
        correct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correct1ActionPerformed(evt);
            }
        });

        correct2.setBackground(new java.awt.Color(251, 240, 229));
        correct2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correct2.setForeground(new java.awt.Color(47, 110, 31));
        correct2.setText("SIMOUN");
        correct2.setBorder(null);
        correct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correct2ActionPerformed(evt);
            }
        });

        correct3.setBackground(new java.awt.Color(251, 240, 229));
        correct3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correct3.setForeground(new java.awt.Color(47, 110, 31));
        correct3.setText("ELIAS");
        correct3.setBorder(null);
        correct3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correct3ActionPerformed(evt);
            }
        });

        correct4.setBackground(new java.awt.Color(251, 240, 229));
        correct4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correct4.setForeground(new java.awt.Color(47, 110, 31));
        correct4.setText("MARIA CLARA");
        correct4.setBorder(null);
        correct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correct4ActionPerformed(evt);
            }
        });

        correct5.setBackground(new java.awt.Color(251, 240, 229));
        correct5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correct5.setForeground(new java.awt.Color(47, 110, 31));
        correct5.setText("PADRE DAMASO");
        correct5.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correct5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correct2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correct3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correct4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(question1)
                        .addComponent(NEIL1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(question2)
                        .addComponent(NEIL2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(question3)
                        .addComponent(NEIL3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(question4)
                        .addComponent(NEIL4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(question5)
                        .addComponent(NEIL5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nextbuttonIDEN))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(correct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(correct2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(correct3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(correct4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(correct5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3))
                    .addGap(5, 5, 5)
                    .addComponent(question1)
                    .addGap(1, 1, 1)
                    .addComponent(NEIL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(question2)
                    .addGap(1, 1, 1)
                    .addComponent(NEIL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(question3)
                    .addGap(1, 1, 1)
                    .addComponent(NEIL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(question4)
                    .addGap(1, 1, 1)
                    .addComponent(NEIL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(question5)
                    .addGap(1, 1, 1)
                    .addComponent(NEIL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(nextbuttonIDEN)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NEIL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEIL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEIL1ActionPerformed

    private void NEIL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEIL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEIL2ActionPerformed

    private void NEIL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEIL3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEIL3ActionPerformed

    private void NEIL4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEIL4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEIL4ActionPerformed

    private void NEIL5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEIL5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEIL5ActionPerformed

    private void nextbuttonIDENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonIDENActionPerformed
new multichoice().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextbuttonIDENActionPerformed

    private void correct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correct2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correct2ActionPerformed

    private void correct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correct4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correct4ActionPerformed

    private void correct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correct1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correct1ActionPerformed

    private void correct3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correct3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correct3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(correctidentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(correctidentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(correctidentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(correctidentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new correctidentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField NEIL1;
    public static javax.swing.JTextField NEIL2;
    public static javax.swing.JTextField NEIL3;
    public static javax.swing.JTextField NEIL4;
    public static javax.swing.JTextField NEIL5;
    private javax.swing.JTextField correct1;
    private javax.swing.JTextField correct2;
    private javax.swing.JTextField correct3;
    private javax.swing.JTextField correct4;
    private javax.swing.JTextField correct5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton nextbuttonIDEN;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question5;
    // End of variables declaration//GEN-END:variables
}
