/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapp;

/**
 *
 * @author nejac
 */
public class resulta extends javax.swing.JFrame {
public void useData() {
    }
    
    /**
     * Creates new form resulta
     */
    public resulta() {
        initComponents();
        setResizable(false);
        String stringedSCOREiden = Integer.toString(identification.idenSCORE);
        System.out.println("Shared Value: " + stringedSCOREiden);
        
        String stringedSCOREmulti = Integer.toString(multichoice.multiSCORE);
        System.out.println("Shared Value: " + stringedSCOREmulti);
        
        String stringedSCOREboolean = Integer.toString(trueorfalse.TFSCORE);
        
        int FINALITY = identification.idenSCORE + multichoice.multiSCORE + trueorfalse.TFSCORE;
        String stringedSCOREfinal = Integer.toString(FINALITY);
        
        idenTOTAL.setText(stringedSCOREiden);
        multiTOTAL.setText(stringedSCOREmulti);
        trueorfalseTOTAL.setText(stringedSCOREboolean);
        TOTALITYFINAL.setText(stringedSCOREfinal);
        
        if (FINALITY >= 9)
                verdict.setText("You Passed!");
        else
            verdict.setText("You Failed...");
        
        if (FINALITY == 0)
            rating.setText("0%");
        if (FINALITY == 1)
            rating.setText("6.66%");
        if (FINALITY == 2)
            rating.setText("13.33%");
        if (FINALITY == 3)
            rating.setText("20%");
        if (FINALITY == 4)
            rating.setText("26.66%");
        if (FINALITY == 5)
            rating.setText("33.33%");
        if (FINALITY == 6)
            rating.setText("40%");
        if (FINALITY == 7)
            rating.setText("46.66%");
        if (FINALITY == 8)
            rating.setText("53.33%");
        if (FINALITY == 9)
            rating.setText("60%");
        if (FINALITY == 10)
            rating.setText("66.66%");
        if (FINALITY == 11)
            rating.setText("73.33%");
        if (FINALITY == 12)
            rating.setText("80%");
        if (FINALITY == 13)
            rating.setText("86.66%");
        if (FINALITY == 14)
            rating.setText("93.33%");
        if (FINALITY == 15)
            rating.setText("100%");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        trueorfalseTOTAL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        idenTOTAL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        multiTOTAL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TOTALITYFINAL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        verdict = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rating = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(251, 240, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(148, 114, 97));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trueorfalseTOTAL.setEditable(false);
        trueorfalseTOTAL.setBackground(new java.awt.Color(251, 240, 229));
        trueorfalseTOTAL.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        trueorfalseTOTAL.setText("0");
        trueorfalseTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueorfalseTOTALActionPerformed(evt);
            }
        });
        jPanel3.add(trueorfalseTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, -1));

        jLabel7.setBackground(new java.awt.Color(251, 240, 229));
        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(251, 240, 229));
        jLabel7.setText("TRUE OR FALSE");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setBackground(new java.awt.Color(251, 240, 229));
        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(251, 240, 229));
        jLabel8.setText("SCORE");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 151, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 210, 130));

        jPanel4.setBackground(new java.awt.Color(108, 82, 75));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idenTOTAL.setEditable(false);
        idenTOTAL.setBackground(new java.awt.Color(251, 240, 229));
        idenTOTAL.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        idenTOTAL.setText("0");
        idenTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idenTOTALActionPerformed(evt);
            }
        });
        jPanel4.add(idenTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, -1));

        jLabel4.setBackground(new java.awt.Color(251, 240, 229));
        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 240, 229));
        jLabel4.setText("IDENTIFICATION");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 151, -1));

        jLabel9.setBackground(new java.awt.Color(251, 240, 229));
        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(251, 240, 229));
        jLabel9.setText("SCORE");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 151, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        jPanel5.setBackground(new java.awt.Color(121, 94, 82));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        multiTOTAL.setEditable(false);
        multiTOTAL.setBackground(new java.awt.Color(251, 240, 229));
        multiTOTAL.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        multiTOTAL.setText("0");
        multiTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiTOTALActionPerformed(evt);
            }
        });
        jPanel5.add(multiTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 109, -1));

        jLabel2.setBackground(new java.awt.Color(251, 240, 229));
        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 240, 229));
        jLabel2.setText("MULTIPLE CHOICE");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setBackground(new java.awt.Color(251, 240, 229));
        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 240, 229));
        jLabel6.setText("SCORE");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 151, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 210, 130));

        TOTALITYFINAL.setEditable(false);
        TOTALITYFINAL.setBackground(new java.awt.Color(108, 82, 75));
        TOTALITYFINAL.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        TOTALITYFINAL.setForeground(new java.awt.Color(251, 240, 229));
        TOTALITYFINAL.setText("0");
        TOTALITYFINAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALITYFINALActionPerformed(evt);
            }
        });
        jPanel2.add(TOTALITYFINAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        jLabel1.setBackground(new java.awt.Color(251, 240, 229));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 82, 75));
        jLabel1.setText("you want to exit.");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 120, 20));

        jLabel16.setBackground(new java.awt.Color(251, 240, 229));
        jLabel16.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(108, 82, 75));
        jLabel16.setText("THANK YOU!");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 90, -1));

        jLabel17.setBackground(new java.awt.Color(251, 240, 229));
        jLabel17.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(108, 82, 75));
        jLabel17.setText("Close the window when");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 160, 20));

        verdict.setEditable(false);
        verdict.setBackground(new java.awt.Color(108, 82, 75));
        verdict.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        verdict.setForeground(new java.awt.Color(251, 240, 229));
        verdict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdictActionPerformed(evt);
            }
        });
        jPanel2.add(verdict, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 150, -1));

        jLabel5.setBackground(new java.awt.Color(108, 82, 75));
        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(108, 82, 75));
        jLabel5.setText("TOTAL SCORE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, -1));

        jLabel10.setBackground(new java.awt.Color(108, 82, 75));
        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(108, 82, 75));
        jLabel10.setText("VERDICT IS...");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 160, -1));

        jLabel11.setBackground(new java.awt.Color(108, 82, 75));
        jLabel11.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(108, 82, 75));
        jLabel11.setText("RATING");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 160, -1));

        rating.setEditable(false);
        rating.setBackground(new java.awt.Color(108, 82, 75));
        rating.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        rating.setForeground(new java.awt.Color(251, 240, 229));
        rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingActionPerformed(evt);
            }
        });
        jPanel2.add(rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 150, -1));

        jButton1.setBackground(new java.awt.Color(108, 82, 75));
        jButton1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jButton1.setText("Retry Quiz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 140, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 238, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(642, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idenTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idenTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idenTOTALActionPerformed

    private void multiTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiTOTALActionPerformed

    private void trueorfalseTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueorfalseTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trueorfalseTOTALActionPerformed

    private void TOTALITYFINALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALITYFINALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOTALITYFINALActionPerformed

    private void verdictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verdictActionPerformed

    private void ratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        identification.idenSCORE = 0;
        multichoice.multiSCORE = 0;
        trueorfalse.TFSCORE = 0;
        new identification().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField TOTALITYFINAL;
    public static javax.swing.JTextField idenTOTAL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JTextField multiTOTAL;
    private javax.swing.JTextField rating;
    public static javax.swing.JTextField trueorfalseTOTAL;
    private javax.swing.JTextField verdict;
    // End of variables declaration//GEN-END:variables
}
