package javaapp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Christopher
 */
public class trueorfalseANSWERS extends javax.swing.JFrame {
public static int TFSCORE = 0;
public static boolean Q1correct = false, Q2correct = false, Q3correct = false, Q4correct = false, Q5correct = false;
public static boolean F1s = false, F2s = false, T3s = false, T4s = false, F5s = false;

    /**
     * Creates new form TRUEFALSENOLIANDELFILI
     */
    public trueorfalseANSWERS() {
        initComponents();
        setResizable(false);
        buttonGroup1.add(T1);
        buttonGroup1.add(F1);
        buttonGroup2.add(T2);
        buttonGroup2.add(F2);
        buttonGroup3.add(T3);
        buttonGroup3.add(F3);
        buttonGroup4.add(T4);
        buttonGroup4.add(F4); 
        buttonGroup5.add(T5); 
        buttonGroup5.add(F5); 
        
        if (trueorfalse.Q1correct == false){
            correctANS1.setText("CORRECT ANSWER");
            F1.setSelected(true);
        } else {
            correctshower1.setText("CORRECT");
            T1.setSelected(true);
        }
        
        if (trueorfalse.Q2correct == false){
            correctANS2.setText("CORRECT ANSWER");
            F2.setSelected(true);
        } else {
            correctshower2.setText("CORRECT");
            T2.setSelected(true);
        }
        
        if (trueorfalse.Q3correct == false){
            correctANS3.setText("CORRECT ANSWER");
            T3.setSelected(true);
        } else {
            correctshower3.setText("CORRECT");
            F3.setSelected(true);
        }
        
        if (trueorfalse.Q4correct == false){
            correctANS4.setText("CORRECT ANSWER");
            T4.setSelected(true);
        } else {
            correctshower4.setText("CORRECT");
            F4.setSelected(true);
        }
        
        if (trueorfalse.Q5correct == false){
            correctANS5.setText("CORRECT ANSWER");
            F5.setSelected(true);
        } else {
            correctshower5.setText("CORRECT");
            T5.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        T1 = new javax.swing.JRadioButton();
        F1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T2 = new javax.swing.JRadioButton();
        F2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        T3 = new javax.swing.JRadioButton();
        F3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        T4 = new javax.swing.JRadioButton();
        F4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        T5 = new javax.swing.JRadioButton();
        F5 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        NEXT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        correctANS1 = new javax.swing.JTextField();
        correctANS2 = new javax.swing.JTextField();
        correctANS3 = new javax.swing.JTextField();
        correctANS4 = new javax.swing.JTextField();
        correctANS5 = new javax.swing.JTextField();
        correctshower1 = new javax.swing.JTextField();
        correctshower2 = new javax.swing.JTextField();
        correctshower3 = new javax.swing.JTextField();
        correctshower4 = new javax.swing.JTextField();
        correctshower5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 132, 152, -1));

        jPanel1.setBackground(new java.awt.Color(251, 240, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T1.setText("TRUE");
        T1.setEnabled(false);
        jPanel1.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 98, -1));

        F1.setText("FALSE");
        F1.setEnabled(false);
        jPanel1.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 98, -1));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 82, 75));
        jLabel1.setText("TRUE OR FALSE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 152, -1));

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 82, 75));
        jLabel3.setText("Check True if the sentence is correct and if it is False");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 480, -1));

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(108, 82, 75));
        jLabel4.setText("1. José Rizal wrote Noli Me Tangere and El Filibusterismo. ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 446, -1));

        T2.setText("TRUE");
        T2.setEnabled(false);
        jPanel1.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 98, -1));

        F2.setText("FALSE");
        F2.setEnabled(false);
        jPanel1.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 98, -1));

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(108, 82, 75));
        jLabel5.setText("2. Crisostomo Ibarra is the main character in El Filibusterismo. ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 446, -1));

        T3.setText("TRUE");
        T3.setEnabled(false);
        jPanel1.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 98, -1));

        F3.setText("FALSE");
        F3.setEnabled(false);
        jPanel1.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 98, -1));

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(108, 82, 75));
        jLabel6.setText("3. El Filibusterismo was written before Noli Me Tangere. ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 446, -1));

        T4.setText("TRUE");
        T4.setEnabled(false);
        jPanel1.add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 98, -1));

        F4.setText("FALSE");
        F4.setEnabled(false);
        jPanel1.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 98, -1));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(108, 82, 75));
        jLabel7.setText("4. Maria Clara is Crisostomo Ibarra's mother. ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 446, -1));

        T5.setText("TRUE");
        T5.setEnabled(false);
        jPanel1.add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 98, -1));

        F5.setText("FALSE");
        F5.setEnabled(false);
        jPanel1.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 98, -1));

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(108, 82, 75));
        jLabel8.setText("in the Philippines");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 611, -1));

        NEXT.setBackground(new java.awt.Color(108, 82, 75));
        NEXT.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        NEXT.setText("NEXT");
        NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXTActionPerformed(evt);
            }
        });
        jPanel1.add(NEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(108, 82, 75));
        jLabel9.setText("5. Both Noli Me Tangere and El Filibusterismo talk about the Spanish colonization");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 611, -1));

        correctANS1.setBackground(new java.awt.Color(251, 240, 229));
        correctANS1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correctANS1.setForeground(new java.awt.Color(47, 110, 31));
        correctANS1.setBorder(null);
        correctANS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctANS1ActionPerformed(evt);
            }
        });
        jPanel1.add(correctANS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        correctANS2.setBackground(new java.awt.Color(251, 240, 229));
        correctANS2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correctANS2.setForeground(new java.awt.Color(47, 110, 31));
        correctANS2.setBorder(null);
        correctANS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctANS2ActionPerformed(evt);
            }
        });
        jPanel1.add(correctANS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        correctANS3.setBackground(new java.awt.Color(251, 240, 229));
        correctANS3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correctANS3.setForeground(new java.awt.Color(47, 110, 31));
        correctANS3.setBorder(null);
        correctANS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctANS3ActionPerformed(evt);
            }
        });
        jPanel1.add(correctANS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        correctANS4.setBackground(new java.awt.Color(251, 240, 229));
        correctANS4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correctANS4.setForeground(new java.awt.Color(47, 110, 31));
        correctANS4.setBorder(null);
        correctANS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctANS4ActionPerformed(evt);
            }
        });
        jPanel1.add(correctANS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        correctANS5.setBackground(new java.awt.Color(251, 240, 229));
        correctANS5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correctANS5.setForeground(new java.awt.Color(47, 110, 31));
        correctANS5.setBorder(null);
        correctANS5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctANS5ActionPerformed(evt);
            }
        });
        jPanel1.add(correctANS5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        correctshower1.setBackground(new java.awt.Color(251, 240, 229));
        correctshower1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correctshower1.setForeground(new java.awt.Color(47, 110, 31));
        correctshower1.setBorder(null);
        correctshower1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctshower1ActionPerformed(evt);
            }
        });
        jPanel1.add(correctshower1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        correctshower2.setBackground(new java.awt.Color(251, 240, 229));
        correctshower2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correctshower2.setForeground(new java.awt.Color(47, 110, 31));
        correctshower2.setBorder(null);
        correctshower2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctshower2ActionPerformed(evt);
            }
        });
        jPanel1.add(correctshower2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        correctshower3.setBackground(new java.awt.Color(251, 240, 229));
        correctshower3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correctshower3.setForeground(new java.awt.Color(47, 110, 31));
        correctshower3.setBorder(null);
        correctshower3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctshower3ActionPerformed(evt);
            }
        });
        jPanel1.add(correctshower3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        correctshower4.setBackground(new java.awt.Color(251, 240, 229));
        correctshower4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correctshower4.setForeground(new java.awt.Color(47, 110, 31));
        correctshower4.setBorder(null);
        correctshower4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctshower4ActionPerformed(evt);
            }
        });
        jPanel1.add(correctshower4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        correctshower5.setBackground(new java.awt.Color(251, 240, 229));
        correctshower5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        correctshower5.setForeground(new java.awt.Color(47, 110, 31));
        correctshower5.setBorder(null);
        correctshower5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctshower5ActionPerformed(evt);
            }
        });
        jPanel1.add(correctshower5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 580));

        setSize(new java.awt.Dimension(612, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXTActionPerformed

        new resulta().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NEXTActionPerformed

    private void correctANS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctANS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctANS1ActionPerformed

    private void correctANS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctANS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctANS2ActionPerformed

    private void correctANS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctANS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctANS3ActionPerformed

    private void correctANS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctANS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctANS4ActionPerformed

    private void correctANS5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctANS5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctANS5ActionPerformed

    private void correctshower1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctshower1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctshower1ActionPerformed

    private void correctshower2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctshower2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctshower2ActionPerformed

    private void correctshower3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctshower3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctshower3ActionPerformed

    private void correctshower4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctshower4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctshower4ActionPerformed

    private void correctshower5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctshower5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctshower5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trueorfalseANSWERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trueorfalseANSWERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trueorfalseANSWERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trueorfalseANSWERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trueorfalseANSWERS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton F1;
    private javax.swing.JRadioButton F2;
    private javax.swing.JRadioButton F3;
    private javax.swing.JRadioButton F4;
    private javax.swing.JRadioButton F5;
    private javax.swing.JButton NEXT;
    private javax.swing.JRadioButton T1;
    private javax.swing.JRadioButton T2;
    private javax.swing.JRadioButton T3;
    private javax.swing.JRadioButton T4;
    private javax.swing.JRadioButton T5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JTextField correctANS1;
    private javax.swing.JTextField correctANS2;
    private javax.swing.JTextField correctANS3;
    private javax.swing.JTextField correctANS4;
    private javax.swing.JTextField correctANS5;
    private javax.swing.JTextField correctshower1;
    private javax.swing.JTextField correctshower2;
    private javax.swing.JTextField correctshower3;
    private javax.swing.JTextField correctshower4;
    private javax.swing.JTextField correctshower5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
