package javaapp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Christopher
 */
public class trueorfalse extends javax.swing.JFrame {
public static int TFSCORE = 0;
public static boolean Q1correct = false, Q2correct = false, Q3correct = false, Q4correct = false, Q5correct = false;
public static boolean F1s = false, F2s = false, T3s = false, T4s = false, F5s = false;

    /**
     * Creates new form TRUEFALSENOLIANDELFILI
     */
    public trueorfalse() {
        initComponents();
        setResizable(false);
        buttonGroup1.add(T1);
        buttonGroup1.add(F1);
        buttonGroup2.add(T2);
        buttonGroup2.add(F2);
        buttonGroup3.add(T3);
        buttonGroup3.add(F3);
        buttonGroup4.add(T4);
        buttonGroup4.add(F4); 
        buttonGroup5.add(T5); 
        buttonGroup5.add(F5); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        T1 = new javax.swing.JRadioButton();
        F1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T2 = new javax.swing.JRadioButton();
        F2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        T3 = new javax.swing.JRadioButton();
        F3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        T4 = new javax.swing.JRadioButton();
        F4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        T5 = new javax.swing.JRadioButton();
        F5 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        NEXT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 132, 152, -1));

        jPanel1.setBackground(new java.awt.Color(251, 240, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T1.setText("TRUE");
        jPanel1.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 98, -1));

        F1.setText("FALSE");
        jPanel1.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 98, -1));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 82, 75));
        jLabel1.setText("TRUE OR FALSE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 152, -1));

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 82, 75));
        jLabel3.setText("Check True if the sentence is correct and if it is False");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 392, -1));

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(108, 82, 75));
        jLabel4.setText("1. José Rizal wrote Noli Me Tangere and El Filibusterismo. ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 446, -1));

        T2.setText("TRUE");
        jPanel1.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 98, -1));

        F2.setText("FALSE");
        jPanel1.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 98, -1));

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(108, 82, 75));
        jLabel5.setText("2. Crisostomo Ibarra is the main character in El Filibusterismo. ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 446, -1));

        T3.setText("TRUE");
        jPanel1.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 98, -1));

        F3.setText("FALSE");
        jPanel1.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 98, -1));

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(108, 82, 75));
        jLabel6.setText("3. El Filibusterismo was written before Noli Me Tangere. ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 446, -1));

        T4.setText("TRUE");
        jPanel1.add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 98, -1));

        F4.setText("FALSE");
        jPanel1.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 98, -1));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(108, 82, 75));
        jLabel7.setText("4. Maria Clara is Crisostomo Ibarra's mother. ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 446, -1));

        T5.setText("TRUE");
        jPanel1.add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 98, -1));

        F5.setText("FALSE");
        jPanel1.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 98, -1));

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(108, 82, 75));
        jLabel8.setText("in the Philippines");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 611, -1));

        NEXT.setBackground(new java.awt.Color(108, 82, 75));
        NEXT.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        NEXT.setText("NEXT");
        NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXTActionPerformed(evt);
            }
        });
        jPanel1.add(NEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(108, 82, 75));
        jLabel9.setText("5. Both Noli Me Tangere and El Filibusterismo talk about the Spanish colonization");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 611, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 580));

        setSize(new java.awt.Dimension(612, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXTActionPerformed
        if (T1.isSelected()) {
            ++TFSCORE;
            Q1correct = true;
        }
        if (T2.isSelected()) {
            ++TFSCORE;
            Q2correct = true;
        }
        if (F3.isSelected()) {
            ++TFSCORE;
            Q3correct = true;
        }
        if (F4.isSelected()) {
            ++TFSCORE;
            Q4correct = true;
        }
        if (T5.isSelected()) {
            ++TFSCORE;
            Q5correct = true;
        }
        new trueorfalseANSWERS().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NEXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trueorfalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trueorfalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trueorfalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trueorfalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trueorfalse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton F1;
    private javax.swing.JRadioButton F2;
    private javax.swing.JRadioButton F3;
    private javax.swing.JRadioButton F4;
    private javax.swing.JRadioButton F5;
    private javax.swing.JButton NEXT;
    private javax.swing.JRadioButton T1;
    private javax.swing.JRadioButton T2;
    private javax.swing.JRadioButton T3;
    private javax.swing.JRadioButton T4;
    private javax.swing.JRadioButton T5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
